Update for v200.2 release
Esri/arcgis-maps-sdk-swift pull request #8
Opened 2023-08-15 01:08 UTC by saratchandrakarumuri

2023-08-15 09:40 UTC, dg0yal requested changes
200.2 Needs xcode 14.1 or higher

2023-08-15 18:05 UTC, saratchandrakarumuri commented
@dg0yal Updated the Xcode requirements in readme page

2023-08-15 20:52 UTC, zkline101 approved these changes

2023-08-16 06:37 UTC, dg0yal approved these changes

2023-08-16 15:40 UTC, merged